/*
   Copyright (c) 2024 - 2025 Sibi Siddharthan

   Distributed under the MIT license.
   Refer to the LICENSE file at the root directory for details.
*/

#ifndef SPGP_ERROR_H
#define SPGP_ERROR_H

typedef enum _pgp_error_t
{
	// No error
	PGP_SUCCESS = 0,

	// General errors
	PGP_NO_MEMORY,
	PGP_INSUFFICIENT_DATA,
	PGP_INVALID_PARAMETER,
	PGP_INCORRECT_FUNCTION,
	PGP_EMPTY_PASSPHRASE,
	PGP_INTERNAL_BUG,

	// Packet errors
	PGP_MALFORMED_PACKET_HEADER,
	PGP_MALFORMED_PACKET_LEGACY_HEADER,
	PGP_MALFORMED_SUBPACKET_HEADER,
	PGP_MALFORMED_PARTIAL_LENGTH_HEADER,
	PGP_INVALID_HEADER_FORMAT,
	PGP_INVALID_PACKET_TAG,
	PGP_INVALID_PARTIAL_PACKET_TYPE,
	PGP_INVALID_PARTIAL_PACKET_START_SIZE,
	PGP_UNKNOWN_CRITICAL_SUBPACKET,
	PGP_EMPTY_PACKET,

	// Cryptographic errors
	PGP_RAND_ERROR,
	PGP_INVALID_CIPHER_ALGORITHM,
	PGP_INVALID_PUBLIC_ALGORITHM,
	PGP_INVALID_AEAD_ALGORITHM,
	PGP_INVALID_AEAD_CIPHER_PAIR,
	PGP_INVALID_SIGNATURE_ALGORITHM,
	PGP_UNSUPPORTED_SIGNATURE_ALGORITHM,
	PGP_INVALID_KEY_EXCHANGE_ALGORITHM,
	PGP_INVALID_HASH_ALGORITHM,
	PGP_INVALID_CFB_IV_SIZE,
	PGP_INVALID_AEAD_IV_SIZE,
	PGP_INVALID_HASH_SALT_SIZE,
	PGP_EMPTY_IV,
	PGP_MDC_TAG_MISMATCH,
	PGP_AEAD_TAG_MISMATCH,
	PGP_QUICK_HASH_MISMATCH,

	// S2K errors
	PGP_INVALID_S2K_USAGE,
	PGP_INVALID_S2K_SPECIFIER,
	PGP_MALFORMED_S2K_SIZE,
	PGP_EMPTY_S2K,

	// Key errors
	PGP_MALFORMED_KEY,
	PGP_INVALID_KEY_VERSION,
	PGP_INVALID_KEY_TYPE,

	PGP_MALFORMED_PUBLIC_KEY_PACKET,
	PGP_MALFORMED_SECRET_KEY_PACKET,
	PGP_MALFORMED_PUBLIC_KEY_COUNT,
	PGP_MALFORMED_SECRET_KEY_COUNT,
	PGP_MALFORMED_KEYDEF_PACKET,

	PGP_EMPTY_PUBLIC_KEY,
	PGP_EMPTY_SECRET_KEY,

	PGP_MALFORMED_RSA_PUBLIC_KEY,
	PGP_MALFORMED_ELGAMAL_PUBLIC_KEY,
	PGP_MALFORMED_DSA_PUBLIC_KEY,
	PGP_MALFORMED_ECDSA_PUBLIC_KEY,
	PGP_MALFORMED_EDDSA_PUBLIC_KEY,
	PGP_MALFORMED_ECDH_PUBLIC_KEY,
	PGP_MALFORMED_X25519_PUBLIC_KEY,
	PGP_MALFORMED_X448_PUBLIC_KEY,
	PGP_MALFORMED_ED25519_PUBLIC_KEY,
	PGP_MALFORMED_ED448_PUBLIC_KEY,

	PGP_MALFORMED_RSA_SECRET_KEY,
	PGP_MALFORMED_ELGAMAL_SECRET_KEY,
	PGP_MALFORMED_DSA_SECRET_KEY,
	PGP_MALFORMED_ECDSA_SECRET_KEY,
	PGP_MALFORMED_EDDSA_SECRET_KEY,
	PGP_MALFORMED_ECDH_SECRET_KEY,
	PGP_MALFORMED_X25519_SECRET_KEY,
	PGP_MALFORMED_X448_SECRET_KEY,
	PGP_MALFORMED_ED25519_SECRET_KEY,
	PGP_MALFORMED_ED448_SECRET_KEY,

	PGP_ENCRYPTION_KEY_TOO_BIG,
	PGP_KEY_CHECKSUM_MISMATCH,

	PGP_ENCRYPTION_ERROR,
	PGP_DECRYPTION_ERROR,

	PGP_UNUSABLE_KEY_FOR_CERTIFICATION,
	PGP_UNUSABLE_KEY_FOR_SIGNING,
	PGP_UNUSABLE_KEY_FOR_ENCRYPTION,
	PGP_UNUSABLE_KEY_FOR_AUTHENTICATION,

	PGP_UNSUPPORTED_ALGORITHM_FOR_V6_KEY,
	PGP_UNSUPPORTED_ALGORITHM_FOR_V5_KEY,
	PGP_UNSUPPORTED_ALGORITHM_FOR_V4_KEY,

	PGP_RSA_KEY_UNSUPPORTED_BIT_SIZE,
	PGP_RSA_KEY_GENERATION_FAILURE,
	PGP_DSA_KEY_UNSUPPORTED_BIT_SIZE,
	PGP_DSA_KEY_GENERATION_FAILURE,
	PGP_ELGAMAL_KEY_UNSUPPORTED_BIT_SIZE,
	PGP_ELGAMAL_KEY_GENERATION_FAILURE,

	PGP_UNSUPPORTED_ELLIPTIC_CURVE,
	PGP_UNSUPPORTED_EDWARDS_CURVE,
	PGP_ELLIPTIC_CURVE_KEY_GENERATION_FAILURE,
	PGP_ECDSA_KEY_GENERATION_FAILURE,
	PGP_EDDSA_KEY_GENERATION_FAILURE,
	PGP_ECDH_KEY_GENERATION_FAILURE,

	PGP_X25519_KEY_GENERATION_FAILURE,
	PGP_X448_KEY_GENERATION_FAILURE,
	PGP_ED25519_KEY_GENERATION_FAILURE,
	PGP_ED448_KEY_GENERATION_FAILURE,

	PGP_KEY_NOT_DECRYPTED,

	// Session errors
	PGP_MALFORMED_RSA_SESSION_KEY,
	PGP_MALFORMED_ELGAMAL_SESSION_KEY,
	PGP_MALFORMED_ECDH_SESSION_KEY,
	PGP_MALFORMED_X25519_SESSION_KEY,
	PGP_MALFORMED_X448_SESSION_KEY,

	PGP_MALFORMED_PUBLIC_SESSION_PACKET,
	PGP_INVALID_PUBLIC_SESSION_PACKET_VERSION,
	PGP_MALFORMED_PUBLIC_SESSION_PACKET_COUNT,

	PGP_INVALID_SYMMETRIC_SESSION_PACKET_VERSION,
	PGP_MALFORMED_SYMMETRIC_SESSION_PACKET_COUNT,
	PGP_MALFORMED_SYMMETRIC_SESSION_PACKET,

	// Signature errors
	PGP_INVALID_SIGNATURE_TYPE,
	PGP_INVALID_SIGNATURE_PACKET_VERSION,
	PGP_MALFORMED_SIGNATURE_PACKET,
	PGP_INVALID_SIGNATURE_SUBPACKET_TAG,
	PGP_MALFORMED_SIGNATURE_PACKET_SALT_SIZE,
	PGP_MALFORMED_SIGNATURE_HASHED_SUBPACKET_SIZE,
	PGP_MALFORMED_SIGNATURE_UNHASHED_SUBPACKET_SIZE,
	PGP_INVALID_ONE_PASS_SIGNATURE_PACKET_VERSION,
	PGP_MALFORMED_ONE_PASS_SIGNATURE_PACKET,

	PGP_MALFORMED_SIGNATURE_CREATION_TIME_SUBPACKET,
	PGP_MALFORMED_SIGNATURE_EXPIRY_TIME_SUBPACKET,
	PGP_MALFORMED_KEY_EXPIRATION_TIME_SUBPACKET,
	PGP_MALFORMED_EXPORTABLE_SUBPACKET,
	PGP_MALFORMED_REVOCABLE_SUBPACKET,
	PGP_MALFORMED_PRIMARY_USER_ID_SUBPACKET,
	PGP_MALFORMED_KEY_SERVER_PREFERENCES_SUBPACKET,
	PGP_MALFORMED_KEY_FLAGS_SUBPACKET,
	PGP_MALFORMED_FEATURES_SUBPACKET,
	PGP_MALFORMED_PREFERRED_SYMMETRIC_CIPHERS_SUBPACKET,
	PGP_MALFORMED_PREFERRED_HASH_ALGORITHMS_SUBPACKET,
	PGP_MALFORMED_PREFERRED_COMPRESSION_ALGORITHMS_SUBPACKET,
	PGP_MALFORMED_PREFERRED_ENCRYPTION_MODES_SUBPACKET,
	PGP_MALFORMED_PREFERRED_AEAD_CIPHERSUITES_SUBPACKET,
	PGP_MALFORMED_ISSUER_FINGERPRINT_SUBPACKET,
	PGP_MALFORMED_RECIPIENT_FINGERPRINT_SUBPACKET,
	PGP_MALFORMED_REGULAR_EXPRESSION_SUBPACKET,
	PGP_MALFORMED_PREFERRED_KEY_SERVER_SUBPACKET,
	PGP_MALFORMED_POLICY_URI_SUBPACKET,
	PGP_MALFORMED_SIGNER_USER_ID_SUBPACKET,
	PGP_MALFORMED_TRUST_SIGNATURE_SUBPACKET,
	PGP_MALFORMED_REVOCATION_KEY_SUBPACKET,
	PGP_MALFORMED_ISSUER_KEY_ID_SUBPACKET,
	PGP_MALFORMED_NOTATION_DATA_SUBPACKET,
	PGP_MALFORMED_REASON_FOR_REVOCATION_SUBPACKET,
	PGP_MALFORMED_SIGNATURE_TARGET_SUBPACKET,
	PGP_MALFORMED_EMBEDDED_SIGNATURE_SUBPACKET,
	PGP_MALFORMED_ATTESTED_CERTIFICATIONS_SUBPACKET,
	PGP_MALFORMED_LITERAL_DATA_META_HASH_SUBPACKET,

	PGP_EMPTY_SIGNATURE,
	PGP_MALFORMED_RSA_SIGNATURE,
	PGP_MALFORMED_DSA_SIGNATURE,
	PGP_MALFORMED_ECDSA_SIGNATURE,
	PGP_MALFORMED_EDDSA_SIGNATURE,
	PGP_MALFORMED_ED25519_SIGNATURE,
	PGP_MALFORMED_ED448_SIGNATURE,

	PGP_RSA_SIGNATURE_GENERATION_FAILURE,
	PGP_DSA_SIGNATURE_GENERATION_FAILURE,

	PGP_INCOMPATIBLE_SIGNATURE_AND_KEY_VERSION,
	PGP_BAD_SIGNATURE,

	PGP_SIGNATURE_SALT_TOO_BIG,
	PGP_INVALID_LITERAL_PACKET_FORMAT_FOR_TEXT_SIGNATURE,

	// Encrypted Packet errors
	PGP_MALFORMED_SEIPD_PACKET,
	PGP_INVALID_SEIPD_PACKET_VERSION,
	PGP_MALFORMED_AEAD_PACKET,
	PGP_INVALID_AEAD_PACKET_VERSION,
	PGP_INVALID_CHUNK_SIZE,

	// Compressed Packet
	PGP_UNSUPPORTED_COMPRESSION_ALGORITHM,
	PGP_UNKNOWN_COMPRESSION_ALGORITHM,
	PGP_MALFORMED_COMPRESSED_PACKET,

	// Marker Packet
	PGP_MALFORMED_MARKER_PACKET,

	// MDC Packet
	PGP_MALFORMED_MDC_PACKET,

	// Literal Packet
	PGP_UNKNOWN_LITERAL_FORMAT,
	PGP_MALFORMED_LITERAL_PACKET,
	PGP_LITERAL_PACKET_INVALID_FILENAME_SIZE,

	// User ID Packet
	PGP_INVALID_USER_ID,
	PGP_EMPTY_USER_ID,

	// User Attribute Packet
	PGP_MALFORMED_USER_ATTRIBUTE_IMAGE,
	PGP_MALFORMED_USER_ATTRIBUTE_ID,
	PGP_INVALID_USER_ATTRIBUTE_SUBPACKET_TAG,

	// Trust Packet
	PGP_INVALID_TRUST_LEVEL,
	PGP_MALFORMED_TRUST_PACKET,

	// Padding Packet
	PGP_EMPTY_PADDING_PACKET,

	// Keyring Packet
	PGP_MALFORMED_KEYRING_PACKET,
	PGP_MALFORMED_KEYRING_PRIMARY_KEY,
	PGP_MALFORMED_KEYRING_SUBKEYS,
	PGP_KEYRING_PACKET_INVALID_SUBKEY_SIZE,
	PGP_KEYRING_PACKET_INVALID_UID_SIZE,

} pgp_error_t;

#endif
