/*
   Copyright (c) 2024-2025 Sibi Siddharthan

   Distributed under the MIT license.
   Refer to the LICENSE file at the root directory for details.
*/

#include <win32/nt.h>
#include <win32/os.h>

#include <status.h>

status_t _os_status(status_t nt_status)
{
	switch (nt_status)
	{
	case STATUS_SUCCESS:
		return OS_STATUS_SUCCESS;

	case STATUS_NO_MEMORY:
	case STATUS_FATAL_MEMORY_EXHAUSTION:
		return OS_STATUS_NO_ACCESS;

	case STATUS_ACCESS_DENIED:
	case STATUS_SHARING_VIOLATION:
	case STATUS_SECTION_PROTECTION:
	case STATUS_INVALID_OWNER:
		return OS_STATUS_NO_ACCESS;

	case STATUS_CANNOT_DELETE:
	case STATUS_MUTANT_NOT_OWNED:
	case STATUS_PRIVILEGE_NOT_HELD:
		return OS_STATUS_NO_PERMISSION;

	case STATUS_OBJECT_NAME_NOT_FOUND:
	case STATUS_OBJECT_PATH_NOT_FOUND:
		return OS_STATUS_PATH_NOT_FOUND;

	case STATUS_TOO_MANY_OPENED_FILES:
		return OS_STATUS_TOO_MANY_FILES;

	case STATUS_NAME_TOO_LONG:
		return OS_STATUS_NAME_TOO_LONG;

	case STATUS_NOT_A_DIRECTORY:
		return OS_STATUS_NOT_DIRECTORY;

	case STATUS_DIRECTORY_NOT_EMPTY:
		return OS_STATUS_DIRECTORY_NOT_EMPTY;

	case STATUS_OBJECT_NAME_EXISTS:
	case STATUS_OBJECT_NAME_COLLISION:
		return OS_STATUS_PATH_EXISTS;

	case STATUS_INVALID_HANDLE:
		return OS_STATUS_INVALID_HANDLE;

	case STATUS_IO_TIMEOUT:
	case STATUS_IO_UNALIGNED_WRITE:
	case STATUS_FILE_LOCK_CONFLICT:
		return OS_STATUS_IO_ERROR;

	case STATUS_INVALID_PARAMETER:
	case STATUS_ILLEGAL_FUNCTION:
	case STATUS_OBJECT_NAME_INVALID:
	case STATUS_INVALID_EA_NAME:
	case STATUS_EA_LIST_INCONSISTENT:
	case STATUS_SECTION_TOO_BIG:
	case STATUS_MAPPED_ALIGNMENT:
	case STATUS_INVALID_SUB_AUTHORITY:
	case STATUS_INVALID_ACL:
	case STATUS_INVALID_SID:
	case STATUS_INVALID_SECURITY_DESCR:
	case STATUS_IO_REPARSE_DATA_INVALID:
		return OS_STATUS_INVALID_PARAMETER;

	case STATUS_FILE_IS_A_DIRECTORY:
		return OS_STATUS_IS_DIRECTORY;

	case STATUS_PENDING:
		return OS_STATUS_PENDING;

	case STATUS_END_OF_FILE:
	case STATUS_NO_MORE_FILES:
	case STATUS_PIPE_EMPTY:
		return OS_STATUS_END_OF_DATA;

	case STATUS_PIPE_BROKEN:
	case STATUS_PIPE_BUSY:
	case STATUS_PIPE_DISCONNECTED:
	case STATUS_PIPE_NOT_AVAILABLE:
		return OS_STATUS_PIPE_ERROR;

	case STATUS_NOT_SUPPORTED:
	case STATUS_EAS_NOT_SUPPORTED:
		return OS_STATUS_NOT_SUPPORTED;

	case STATUS_INSUFFICIENT_RESOURCES:
	case STATUS_LOCK_NOT_GRANTED:
	case STATUS_RANGE_NOT_LOCKED:
		return OS_STATUS_NOT_LOCKED;

	case STATUS_EA_TOO_LARGE:
	case STATUS_BUFFER_OVERFLOW:
		return OS_STATUS_TOO_BIG;

	case STATUS_TIMEOUT:
		return OS_STATUS_TIMED_OUT;

	default:
		return OS_STATUS_UNKNOWN;
	};
}
