name: spgp CI/CD

on: workflow_dispatch

jobs:
  clang-asan:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4
    - name: Build & Test
      shell: cmd
      run: |
        SET CC=clang
        cmake . -GNinja -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=ON
        ninja
        cd src/crypto
        ctest -VV

  clang-release:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4
    - name: Build & Test
      shell: cmd
      run: |
        SET CC=clang
        cmake . -GNinja -DCMAKE_BUILD_TYPE=Release
        ninja
        cd src/crypto
        ctest -VV

  msvc-release:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4
    - name: Build & Test
      shell: cmd
      run: |
        CALL "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" AMD64
        SET CC=cl
        cmake . -GNinja -DCMAKE_BUILD_TYPE=Release
        ninja
        cd src/crypto
        ctest -VV

  gcc-asan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build & Test
        shell: bash
        run: |
          export CC=gcc
          cmake . -GNinja -DCMAKE_BUILD_TYPE=Debug -DENABLE_ASAN=ON
          ninja
          cd src/crypto
          ctest -VV

  gcc-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build & Test
        shell: bash
        run: |
          export CC=gcc
          cmake . -GNinja -DCMAKE_BUILD_TYPE=Release
          ninja
          cd src/crypto
          ctest -VV

  macos-arm64:
    # Skip for now
    if: false
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Build & Test
        shell: bash
        run: |
          export CC=$(brew --prefix llvm@18)/bin/clang
          cmake . -GNinja -DCMAKE_BUILD_TYPE=Release
          ninja
          cd src/crypto
          ctest -VV
